name: Validate Fastlane Supply Metadata
author: ashutoshgngwr
description: >-
  GitHub action to statically validate Fastlane supply metadata for Android against
  the Play Store listing constraints.
inputs:
  fastlaneDir:
    description: Path of the Fastlane directory
    required: false
    default: ./fastlane
runs:
  using: docker
  image: docker://ashutoshgngwr/validate-fastlane-supply-metadata:v1.2.0
  args:
    - -enable-ga-annotations
    - -fastlane-path=${{ inputs.fastlaneDir }}
branding:
  color: blue
  icon: eye
