name: Validate Fastlane Supply Metadata
author: ashutoshgngwr
description: >-
  GitHub action to statically validate Fastlane supply metadata for Android against
  the Play Store listing constraints.
inputs:
  fastlaneDir:
    description: Path of the Fastlane directory
    required: false
    default: ./fastlane
  usePlayStoreLocales:
    description: Throw error if a locale isn't recognised by Google Play Store
    required: false
    default: "false"
runs:
  using: docker
  image: docker://ashutoshgngwr/validate-fastlane-supply-metadata:v1.4.0
  args:
    - -ga-file-annotations
    - -play-store-locales=${{ inputs.usePlayStoreLocales }}
    - -fastlane-path=${{ inputs.fastlaneDir }}
branding:
  color: blue
  icon: eye
